### Importing tensorflow


In [21]:
import tensorflow as tf

### Creating session

In [7]:
session = tf.Session()

### Hello World! with constant

In [23]:
constant = tf.constant("Hello World!")
session.run(constant)

b'Hello World!'

### Zero matrix of size 2 x 3 

In [16]:
row_dim = 2
col_dim = 3
zeros = tf.zeros([row_dim,col_dim])
session.run(zeros)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

### Variable
* tf.zeros 
* tf.ones 
* tf.fill
* tf.linspace 
* tf.range 
* tf.random_normal
* tf.random_uniform

In [17]:
zerosVariable = tf.Variable(tf.zeros([row_dim, col_dim]))
session.run(zerosVariable.initializer)
session.run(zerosVariable)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [20]:
onceVariable = tf.Variable(tf.once([row_dim, col_dim]))
session.run(onceVariable.initializer)
session.run(onceVariable)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [30]:
fillValue = 5;
constantVariable = tf.Variable(tf.fill([row_dim, col_dim], fillValue))
session.run(constantVariable.initializer)
session.run(constantVariable)

array([[5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [34]:
linspaceVariable = tf.Variable(tf.linspace(start=-5.0,stop=5.0,num=10))
session.run(linspaceVariable.initializer)
session.run(linspaceVariable)

array([-5.        , -3.88888884, -2.77777767, -1.66666651, -0.55555534,
        0.55555582,  1.66666698,  2.77777815,  3.88888931,  5.        ], dtype=float32)

In [36]:
rangeVariable = tf.Variable(tf.range(start=-5, limit=6, delta=2))
session.run(rangeVariable.initializer)
session.run(rangeVariable)

array([-5, -3, -1,  1,  3,  5], dtype=int32)

In [41]:
randomUniformVariable = tf.Variable(tf.random_uniform([row_dim,col_dim],minval=0,maxval=5))
session.run(randomUniformVariable.initializer)
session.run(randomUniformVariable)

array([[ 2.17028332,  4.8918767 ,  3.90390682],
       [ 0.04041314,  3.61296773,  3.17002964]], dtype=float32)

In [42]:
randomNormalVariable = tf.Variable(tf.random_normal([row_dim,col_dim],mean=0.0,stddev=5.0))
session.run(randomNormalVariable.initializer)
session.run(randomNormalVariable)

array([[ -6.80808973, -11.61844635, -11.03033543],
       [ -8.28604317,  -4.2371006 ,  -5.95542908]], dtype=float32)

### Create tensor based on other tensor dimentions
* tf.zeros_like 
* tf.ones_like 

In [27]:
zerosVariableAlike = tf.Variable(tf.zeros_like(zerosVariable))
session.run(zerosVariableAlike.initializer)
session.run(zerosVariableAlike)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

### Create tensor from constant array

In [40]:
constantTensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(session.run(constantTensor))
constantVariable = tf.Variable(constantTensor)
session.run(constantVariable.initializer)
session.run(constantVariable)

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)